language: node_js
node_js: stable

# 只监听 source 分支的改动
branches:
  only:
    - source

# 缓存依赖，节省持续集成时间
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - ./deploy.sh