language: node_js
node_js: stable

# 只监听 source 分支的改动
branches:
  only:
  - source

# 缓存依赖，节省持续集成时间
cache:
  directories:
    - node_modules

install:
    - npm install

script:
    - hexo clean
    - hexo g

deploy:
  local_dir: ./public
  provider: pages
  skip_cleanup: true
  github_token: $token 
  keep_history: true
  on:
    branch: master