baseURL = 'https://blog.coherence.codes/'
languageCode = 'zh-cn'
DefaultContentLanguage = "zh"
title = "Coherence's Blog"
theme = "diary"

[[menu.main]]
url = "/categories"
name = "分类"
weight = 3

[[menu.main]]
url = "/tags"
name = "标签"
weight = 2

[[menu.main]]
url = "/posts"
name = "存档"
weight = 1

[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4

[params]
plausibleAnalyticsServer = "https://analytics.coherence.space"
googleSiteVerification = "3MbbliKSwhNvv713tGB2RL8xvrJC404x1BFONabsw7g"
enableLaTeX=true
