baseURL = 'https://blog.coherence.codes/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh"
title = "Coherence's Blog"
copyright = "Coherence. 本站遵循 CC BY-NC-SA 4.0 协议"
theme = "diary"

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1

[[menu.main]]
url = "/categories"
name = "分类"
weight = 3

[[menu.main]]
url = "/tags"
name = "标签"
weight = 2

[[menu.main]]
url = "/posts"
name = "存档"
weight = 1

[[menu.main]]
url = "/about"
name = "关于"
weight = 4

[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 5

[params]
plausibleAnalyticsServer = "https://analytics.coherence.space"
googleSiteVerification = "3MbbliKSwhNvv713tGB2RL8xvrJC404x1BFONabsw7g"
enableLaTeX=true
